export type OrderDefinition = {
  id: string; name: string; faction: string; category: 'common' | 'classic' | 'advanced' | 'rare' | 'legendary'; description: string; limit?: number
}
// PAFF 2026 - Ordres AUTO.pdf, p. 1, received 2026-10-01.
// Nicolas's October 2 rulings: docs/regles-implementees.md §5.1.
// Historical recruitment order timing remains in force; October 6 adds a separate per-turn budget.
export const orderDefinitions: OrderDefinition[] = [
  { id: 'movement', name: 'Mouvement', faction: 'common', category: 'common', description: 'Déplacer les unités d’une zone selon les conditions de déplacement.' },
  { id: 'shooting', name: 'Tir', faction: 'common', category: 'common', description: 'Faire tirer les unités d’une même zone, hors artillerie.' },
  { id: 'artillery', name: 'Tir Artillerie', faction: 'common', category: 'common', description: 'Faire tirer les artilleries d’une même zone.' },
  { id: 'recruitment', name: 'Recrutement', faction: 'common', category: 'common', limit: 3, description: 'Trois sélections par partie : la première est accessible à partir du tour 2, la deuxième à partir du tour 3, la troisième à partir du tour 4. À partir du tour 2, votre budget de recrutement est renouvelé chaque tour : 3 points plus vos points de stratégie actuels (1 PS = 1 point de recrutement). Le compteur de recrutement permet de suivre et de corriger les dépenses manuellement, indépendamment des sélections restantes de cet ordre. Le placement et les ajustements de recrutement ne dépensent pas automatiquement vos points de stratégie. Recruter sur une case libre de votre Base ou Arrière, dans une zone sans ennemi non engagé. Les recrues peuvent suivre d’autres ordres et tirer dès leur arrivée ce tour-ci.' },
  { id: 'goblin-reinforcements', name: 'Tiens, des gobelins...', faction: 'gobelins', category: 'common', description: 'Vous pouvez recruter gratuitement une Bande de Gobelins.' },
  { id: 'shamanic-boost', name: 'Boost shamanique', faction: 'gobelins', category: 'advanced', limit: 4, description: 'Défaussez une unité de Shamans dans la même zone ou une zone adjacente à une zone contenant vos Archers Gobelins. Ces Archers peuvent tirer une seconde fois ce tour-ci. Vous choisissez la cible de chaque tir.' },
  { id: 'lunch-break', name: 'Pause-déjeuner', faction: 'gobelins', category: 'rare', limit: 2, description: 'Vous pouvez sacrifier une unité gobeline alliée, hors Trolls et Djil, adjacente à une unité de Trolls (même engagée en combat) pour lui ajouter 1 point de R, même au-delà de ses R initiaux. Un seul sacrifice par Troll et par ordre ; vous pouvez ainsi soigner plusieurs Trolls, avec un sacrifice distinct pour chacun. Cet ordre ne permet pas de soigner Djil, meneur de Trolls.' },
  { id: 'great-invocation', name: 'La gross Invokation !', faction: 'gobelins', category: 'legendary', limit: 1, description: 'Sélectionnez une de vos unités de Shamans en jeu, puis lancez 1D6. L’axe concerné est celui du Shaman choisi : sur 1, toutes vos unités gobelines, hors Trolls et Djil, perdent 1 point de R dans les trois axes ; sur 2–3, elles perdent 1 point de R dans cet axe ; sur 4–5, elles doublent leur nombre de dés en attaque et au tir jusqu’à la fin du tour dans cet axe ; sur 6, elles doublent leur nombre de dés en attaque et au tir jusqu’à la fin du tour dans les trois axes. Seuls les dés du profil sont doublés ; les dés supplémentaires des autres effets sont ajoutés ensuite, sans être doublés.' },
  { id: 'strategic-retreat', name: 'Repli stratégique', faction: 'sephosi', category: 'common', description: 'Vous pouvez désengager l’une de vos unités sans subir d’attaque gratuite et sans avoir à déplacer cette unité.' },
  { id: 'concentrated-fire', name: 'Tir concentré', faction: 'sephosi', category: 'advanced', limit: 4, description: 'Sélectionnez une unité ennemie et une zone : vos unités éligibles de cette zone, artillerie comprise, peuvent immédiatement tirer sur cette cible avec un dé supplémentaire chacune, en respectant leurs conditions de tir. Au moins deux unités éligibles de cette même zone doivent tirer sur la cible ; une seule ne suffit pas. Aucun ordre Tir supplémentaire n’est nécessaire.' },
  { id: 'divine-fury', name: 'Fureur divine', faction: 'sephosi', category: 'rare', limit: 2, description: 'Recrutez un ou plusieurs Anges Protecteurs de la Sephosi de votre réserve en payant leur coût avec vos points de recrutement et/ou de stratégie (1 PS = 1 point de recrutement). Déployez-les sur des cases libres de n’importe quelle zone, même contenant des ennemis ou en Base Centre. Aucun ordre Recrutement commun supplémentaire n’est nécessaire.' },
  { id: 'protect-salamander', name: 'Protéger la Salamandre !', faction: 'sephosi', category: 'legendary', limit: 1, description: 'Si votre unité de la Salamandre est engagée en combat, vous pouvez déplacer d’un emplacement vos unités non engagées dans le même axe vers sa zone, même si elles se sont déjà déplacées ou ont déjà tiré. Les unités ainsi déplacées peuvent tirer, y compris une seconde fois ce tour-ci.' },
  { id: 'bran-teha', name: 'Bran Teha', faction: 'gaeli', category: 'common', description: 'Si vous avez une unité de Druides non engagée en combat dans un axe, désignez une unité alliée, même engagée, à portée 3 de ces Druides, selon la même géométrie que le tir et dans le même axe. Lancez 1D6 : sur 5+, l’unité désignée récupère 1 point de R, sans dépasser ses R initiaux.' },
  { id: 'heroic-run', name: 'Course héroique', faction: 'gaeli', category: 'advanced', limit: 4, description: 'Si vous avez une unité de Gardiens des Cen’ dans un axe, considérez cet ordre comme un ordre de Mouvement, mais avec 1 emplacement supplémentaire possible pour les déplacements de vos unités de Vlands (Combattants ou Eclaireurs).' },
  { id: 'call-of-winds', name: 'Appel des vents', faction: 'gaeli', category: 'rare', limit: 2, description: 'Ne peut être joué que si vous avez une unité de Druides non engagée en combat dans l’aire de jeu. Aucun tir, hors artillerie, ne peut être effectué jusqu’à la fin de ce tour.' },
  { id: 'forest-wrath', name: 'Colère de la Forêt', faction: 'gaeli', category: 'legendary', limit: 1, description: 'Si vous avez une unité de Gardiens des Cen’ non engagée en combat, vous pouvez jouer cet ordre. Vos Esprits des Bois doublent uniquement leurs dés de profil au corps à corps jusqu’à la fin du tour, y compris ceux recrutés après l’activation. La mort ou l’engagement ultérieur du Gardien n’annule pas cet effet.' },
]


export function ordersForFaction(faction: string) {
  return orderDefinitions.filter((order) => order.faction === 'common' || order.faction === faction)
}
