export type OrderDefinition = {
  id: string; name: string; faction: string; category: 'common' | 'classic' | 'advanced' | 'rare' | 'legendary'; description: string; limit?: number
}
// PAFF 2026 (3).pdf received 2026-09-18: orders p. 7, recruitment timing p. 3.
// Nicolas corrected Invokation shamanique: 2–3 discards one unit; 4–5 adds no effect.
// Consolidated rulings: docs/differences-regles-2026-09-18.md.
// References for the manual tabletop: effects, limits and timing are player-managed.
export const orderDefinitions: OrderDefinition[] = [
  { id: 'movement', name: 'Mouvement', faction: 'common', category: 'common', description: 'Déplacer les unités d’une zone selon les conditions de déplacement.' },
  { id: 'shooting', name: 'Tir', faction: 'common', category: 'common', description: 'Faire tirer les unités d’une même zone, hors artillerie.' },
  { id: 'artillery', name: 'Tir Artillerie', faction: 'common', category: 'common', description: 'Faire tirer les artilleries d’une même zone.' },
  { id: 'recruitment', name: 'Recrutement', faction: 'common', category: 'common', limit: 3, description: 'Trois sélections par partie : la première est accessible à partir du tour 2, la deuxième à partir du tour 3, la troisième à partir du tour 4. Votre stock reçoit 3 points de recrutement aux tours 2, 4 et 5 ; les points non dépensés sont conservés. Cet ordre permet de dépenser autant de points disponibles que souhaité, complétés si besoin par des points de stratégie (1 PS = 1 point de recrutement), sans ajouter de points au stock. Recruter sur une case libre de votre Base ou Arrière, dans une zone sans ennemi non engagé. Les recrues peuvent suivre d’autres ordres ce tour-ci, mais ne peuvent pas tirer.' },
  { id: 'goblin-reinforcements', name: 'Tiens, des gobelins...', faction: 'gobelins', category: 'common', description: 'Vous pouvez recruter gratuitement une Bande de Gobelins.' },
  { id: 'shamanic-invocation', name: 'Invokation shamanique', faction: 'gobelins', category: 'advanced', limit: 4, description: 'Sélectionnez une de vos unités de Shamans. Elle peut tirer sur une unité ennemie en ajoutant un dé par unité de Shamans à portée de tir. Après le tir, lancez 1D6 : sur 1, défaussez deux Shamans ; sur 2–3, défaussez une unité de Shamans ; sur 4–5, aucun effet supplémentaire ; sur 6, refaites la même attaque sur la même unité (si elle a été détruite, cette attaque ne donne rien).' },
  { id: 'lunch-break', name: 'Pause-déjeuner', faction: 'gobelins', category: 'rare', limit: 2, description: 'Vous pouvez sacrifier une unité gobeline alliée, hors Trolls et Djil, adjacente à une unité de Trolls (même engagée en combat) pour lui ajouter 1 point de R, même au-delà de ses R initiaux. Un seul sacrifice par Troll et par ordre ; vous pouvez ainsi soigner plusieurs Trolls, avec un sacrifice distinct pour chacun. Cet ordre ne permet pas de soigner Djil, meneur de Trolls.' },
  { id: 'great-invocation', name: 'La gross Invokation !', faction: 'gobelins', category: 'legendary', limit: 1, description: 'Sélectionnez une de vos unités de Shamans en jeu, puis lancez 1D6. L’axe concerné est celui du Shaman choisi : sur 1, toutes vos unités gobelines, hors Trolls et Djil, perdent 1 point de R dans les trois axes ; sur 2–3, elles perdent 1 point de R dans cet axe ; sur 4–5, elles doublent leur nombre de dés en attaque et au tir jusqu’à la fin du tour dans cet axe ; sur 6, elles doublent leur nombre de dés en attaque et au tir jusqu’à la fin du tour dans les trois axes. Seuls les dés du profil sont doublés ; les dés supplémentaires des autres effets sont ajoutés ensuite, sans être doublés.' },
  { id: 'strategic-retreat', name: 'Repli stratégique', faction: 'sephosi', category: 'common', description: 'Vous pouvez désengager l’une de vos unités sans subir d’attaque gratuite.' },
  { id: 'concentrated-fire', name: 'Tir concentré', faction: 'sephosi', category: 'advanced', limit: 4, description: 'Sélectionnez une unité ennemie et une zone : vos unités éligibles de cette zone, artillerie comprise, peuvent immédiatement tirer sur cette cible avec un dé supplémentaire chacune, en respectant leurs conditions de tir. Au moins deux unités éligibles de cette même zone doivent tirer sur la cible ; une seule ne suffit pas. Aucun ordre Tir supplémentaire n’est nécessaire.' },
  { id: 'divine-fury', name: 'Fureur divine', faction: 'sephosi', category: 'rare', limit: 2, description: 'Recrutez un ou plusieurs Anges Protecteurs de la Sephosi de votre réserve en payant leur coût avec vos points de recrutement et/ou de stratégie (1 PS = 1 point de recrutement). Déployez-les sur des cases libres de n’importe quelle zone, même contenant des ennemis ou en Base Centre. Aucun ordre Recrutement commun supplémentaire n’est nécessaire.' },
  { id: 'protect-salamander', name: 'Protéger la Salamandre !', faction: 'sephosi', category: 'legendary', limit: 1, description: 'Si votre unité de la Salamandre est engagée en combat dans une zone, toutes vos autres unités ont un bonus de +2 aux dés si elles attaquent des unités dans cette zone.' },
  // Gaeli: PAFF 2026 (4).pdf, received 2026-09-21, p. 7.
  // Tir longue portée is an Archer ability since Nicolas's ruling on 2026-09-30.
  { id: 'heroic-run', name: 'Course héroique', faction: 'gaeli', category: 'advanced', limit: 4, description: 'Si vous avez une unité de Gardiens des Cen’ dans un axe, considérez cet ordre comme un ordre de Mouvement, mais avec 1 emplacement supplémentaire possible pour les déplacements de vos unités de Vlands (Combattants ou Eclaireurs).' },
  { id: 'call-of-winds', name: 'Appel des vents', faction: 'gaeli', category: 'rare', limit: 2, description: 'Ne peut être joué que si vous avez une unité de Druides non engagée en combat dans l’aire de jeu. Aucun tir, hors artillerie, ne peut être effectué jusqu’à la fin de ce tour.' },
  { id: 'summon-spirits', name: 'Convocation des Esprits', faction: 'gaeli', category: 'legendary', limit: 1, description: 'Sacrifiez une unité de Druides afin de recruter gratuitement une unité d’Esprits des Bois à la place.' },
]


export function ordersForFaction(faction: string) {
  return orderDefinitions.filter((order) => order.faction === 'common' || order.faction === faction)
}
